### ISSUE TITLE
analyze.folders() fails to pass sampling to analyze.logfile()

### ISSUE THREAD

**Issue by margarita-zeitlin** [UWCCDL/QEEG#1]
analyze.folders() takes `sampling` as an argument but this variable is not passed to analyze.logfile() so the function proceeds using the default 128 sampling rate. `sampling=sampling` should be added to `analyze.logfile(d, session)` for non-default sampling rates.

**Comment by TheRealDrDre** [comment]
Fixed in version 3.1.5!
